{{- if and .Values.ingress.enabled .Values.ingress.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genqtech-app.fullname" . }}-basic-auth
  labels:
    {{- include "genqtech-app.labels" . | nindent 4 }}
type: Opaque
data:
  # Le contrôleur Ingress Nginx s'attend à une clé nommée 'auth'.
  # La valeur doit être le contenu d'un fichier htpasswd.
  # Nous utilisons la fonction 'htpasswd' de Helm pour générer dynamiquement
  # le mot de passe haché (avec bcrypt) à partir de la valeur en clair fournie.
  auth: {{ htpasswd .Values.ingress.basicAuth.username .Values.ingress.basicAuth.password | b64enc | quote }}
{{- end }}
